version: '3'

services:
  airflow:
    image: apache/airflow:2.2.3
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/traffic_analysis
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
  
    command: ["webserver", "--port", "8080"]
